version: "3"
services:

  node-app:
    build: .
    ports:
      - "4000:2000"
    # volumes:
    #   - ./:/app
    #   - /app/node_modules
    environment:
      - PORT=2000
    # env_file:
    #   - ./.env

  mongo:
    image: mongo
    # restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mba
      - MONGO_INITDB_ROOT_PASSWORD=mba
    volumes:
      - mongo-db:/data/db

volumes:
  mongo-db: