version: "3"
services:
  node-app:
    build: .
    ports:
      - "4000:2000"
    volumes:
      - ./:/app
      - /app/node_modules
    environment:
      - PORT=2000
    # env_file:
    #   - ./.env